### PR TITLE
Fix arrays being expanded without reason

### LINKED ISSUE #42: column_width is not respected everywhere
I see this:

```toml
[tool.ruff]
...
lint.allowed-confusables = [
  "×",
  "’",
]
lint.flake8-type-checking.exempt-modules = [
]
lint.per-file-ignores."*/__init__.py" = [
  "F401",
]
lint.per-file-ignores."docs/*" = [
  "I",
]
lint.per-file-ignores."tests/*" = [
  "D",
]
```

and would rather see

```toml
[tool.ruff]
...
lint.allowed-confusables = [ "×", "’" ]
lint.flake8-type-checking.exempt-modules = []
lint.per-file-ignores."*/__init__.py" = [ "F401" ]
lint.per-file-ignores."docs/*" = [ "I" ]
lint.per-file-ignores."tests/*" = [ "D" ]
```

- `allowed-confusables` is like `tool.hatch.envs.*.features` in that it always contains a short list of strings 
- `lint.per-file-ignores.*` too, those lists are always very short
- I think empty lists should just be on one line always, it looks super weird to expand them.

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #42

before this fix
- :+1: arrays that we *don’t sort* behave as expected (i.e. only get expanded when longer than `column_width`), but
- :-1: arrays that we *do sort* are always expanded into multiple lines
- :+1: arrays are never collapsed, which helps with VCS diffs

after this change
- :+1: single-line arrays are expanded when their lines are longer than `column_width`
- :+1: arrays are still never collapsed

> [!TIP]
> One great thing about this change is that it doesn’t affect formatting at all for people who already use pyproject-fmt. It only affects people who newly adopt it or newly manually added/collapsed arrays

----

I also added `pretty-assertions` to the dev dependencies, because I think everyone agrees that trying to interpret

```
thread 'tests::test_column_width' panicked at rust/src/main.rs:335:9:
assertion `left == right` failed
  left: "[build-system]\nbuild-backend = \"backend\"\nrequires = [ \"c>=1.5\", \"d==2\" ]\n\n[project]\nname = \"beta\"\nclassifiers = [ \"Programming Language :: Python :: 3 :: Only\", \"Programming Language :: Python :: 3.12\" ]\ndependencies = [\n    \"e>=1.5\",\n]\n"
 right: "[build-system]\nbuild-backend = \"backend\"\nrequires = [ \"c>=1.5\", \"d==2\" ]\n\n[project]\nname = \"beta\"\nclassifiers = [\n    \"Programming Language :: Python :: 3 :: Only\",\n    \"Programming Language :: Python :: 3.12\",\n]\ndependencies = [\n    \"e>=1.5\",\n]\n"
```

is much worse than seeing

grafik

### CODE REVIEW

File: rust/src/main.rs [hunk 1]
```diff
@@ -63,16 +63,16 @@ pub fn format_toml(content: &str, opt: &Settings) -> String {
...
+        align_entries: false,         // do not align by =
+        align_comments: true,         // align inline comments
+        align_single_comments: true,  // align comments after entries
+        array_trailing_comma: true,   // ensure arrays finish with trailing comma
+        array_auto_expand: true,      // arrays go to multi line when too long
+        array_auto_collapse: false,   // do not collapse for easier diffs
+        compact_arrays: false,        // leave whitespace
+        compact_inline_tables: false, // leave whitespace
+        compact_entries: false,       // leave whitespace
+        column_width: opt.column_width,
```
Comment (flying-sheep) [inline rust/src/main.rs:75]: I fixed the comments here, because several did not actually describe what the respective option does at all:

- `array_auto_expand: true` is conditional depending on `column_width`, and saying “for easier diffs” implies that it always happens, which is wrong
- `compact_*` has nothing to do with multiline vs single line, these options are about the whitespace within brackets, i.e. `["compact"]` vs `[ "not compact" ]`
- The comment for `column_width` was wrong in multiple ways:
  - “always expand arrays” would happen if you set it to `1`, which isn‘t done here
  - tamasfe/taplo#390 is a VS Code issue and therefore isn’t relevant at all

File: rust/src/global.rs [hunk 2]
```diff
@@ -71,6 +71,7 @@ pub fn reorder_tables(root_ast: &SyntaxNode<Lang>, tables: &mut Tables) {
 #[cfg(test)]
 mod tests {
     use indoc::indoc;
+    use pretty_assertions::assert_eq;
```
Comment (gaborbernat) [inline rust/src/global.rs:74]: This kills Rustrover diffs, let's remove it please.

**Review by gaborbernat — CHANGES_REQUESTED** [review]

File: tests/test_main.py [hunk 3]
```diff
@@ -8,15 +8,11 @@
 def test_format_toml() -> None:
     txt = """
     [project]
-    keywords = [
```
Comment (gaborbernat) [inline tests/test_main.py:11]: The start text shouldn't be changed.

File: rust/src/main.rs [hunk 4]
```diff
@@ -316,4 +317,23 @@ mod tests {
...
+        let start = read_to_string(data.join("column-width.start.toml")).unwrap();
+        let settings = Settings {
+            column_width: 80,
+            indent: 4,
+            keep_full_version: false,
+            max_supported_python: (3, 12),
+            min_supported_python: (3, 12),
+        };
+        let got = format_toml(start.as_str(), &settings);
+        let expected = read_to_string(data.join("column-width.expected.toml")).unwrap();
```
Comment (gaborbernat) [inline rust/src/main.rs:334]: Don't create separate files, inline the test like other tests do.

**Review by gaborbernat — CHANGES_REQUESTED** [review]

File: rust/src/global.rs (hunk 2 above)
Comment (gaborbernat) [reply rust/src/global.rs:74]: I wish could be opt in/out and not always on.

Comment (gaborbernat) [reply rust/src/global.rs:74]: https://github.com/rust-pretty-assertions/rust-pretty-assertions/issues/129

File: tests/test_main.py (hunk 3 above)
Comment (flying-sheep) [reply tests/test_main.py:11]: Changing this test wasn’t about my change modifying test results, it was about more tests covering this code branch.

I can revert changes to this file, but changing both start and expected was deliberate.

Should I revert it?

File: rust/src/main.rs (hunk 4 above)
Comment (flying-sheep) [reply rust/src/main.rs:334]: Will do, but be aware that since I change the settings, this won’t result in adding a parameter to the big parametrized test, it’ll still be a separate test case.

Comment (gaborbernat) [reply rust/src/main.rs:334]: Yeah that is fine.

File: tests/test_main.py (hunk 3 above)
Comment (gaborbernat) [reply tests/test_main.py:11]: Let us keep this as is and add a new test for that 👍

**Review by gaborbernat — APPROVED** [review]
