### PR TITLE
fix: correcting trailing comma when sorting

### LINKED ISSUE #26: Some fields ignore column-width
If you set `column-width`, some fields ignore it and get rewritten anyway. It should be noted that `column-width` does seem to respect trailing commas, so `a = [ "b",\n]` is kept even if it's set. (Also, I think it should be clarified in the docs that the column width is in characters, not entries).

Before:

```toml
[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
keywords = [ "package" ]
authors = [ { name = "Kitware" } ]
dynamic = [ "version" ]
dependencies = [ "sphinx" ]

[tool.hatch]
build.targets.wheel.packages = [ "sphinxcontrib" ]

[tool.pytest.ini_options]
testpaths = [ "tests" ]

[tool.pyproject-fmt]
column_width = 80
```

After:

```toml
[build-system]
build-backend = "hatchling.build"
requires = [
  "hatchling",
]

[project]
keywords = [
  "package",
]
authors = [ { name = "Kitware" } ]
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dynamic = [
  "version",
]
dependencies = [
  "sphinx",
]

[tool.hatch]
build.targets.wheel.packages = [ "sphinxcontrib" ]

[tool.pyproject-fmt]
column_width = 80

[tool.pytest.ini_options]
testpaths = [ "tests" ]
```

This does seem to be happening on sorted fields. I think the presence of the trailing comma should be kept for sorting.

### PR DESCRIPTION
**Pull request by henryiii**
Taplo respects trailing commas when column-width is set ("magic commas" in Black terms). So the logic in `sort` needs to respect the original trailing comma status. Fix #26.

### CODE REVIEW

File: rust/src/helpers/array.rs [hunk 1]
```diff
@@ -211,30 +202,23 @@ mod tests {
...
     #[case::newline_single(
         indoc ! {r#"
-    a = [
-      "A"
-    ]
+    a = ["A"]
     "#},
         indoc ! {r#"
-    a = [
-      "A",
```
Comment (gaborbernat) [inline rust/src/helpers/array.rs:236]: I consider this regression, because now adding a new line no longer it's diff friendly 🤔

Comment (henryiii) [reply rust/src/helpers/array.rs:236]: If there's no trailing comma, it behaves like black, it's not expanded. There are lots of lists that you don't expect to change much, so you can save 66% space by making small arrays (less than column width) one line using the comma at the end.

But sadly this is only opt-in, normally the column-width is set to 1. I changed the column-width to 80 for this test, otherwise the test would always force to multiline, which also always forces the addition of the final comma.

Comment (gaborbernat) [reply rust/src/helpers/array.rs:236]: 👍

Comment (henryiii) [reply rust/src/helpers/array.rs:236]: (The broken test is a regression, though!)

Comment (henryiii) [reply rust/src/helpers/array.rs:236]: Also, keep in mind this is the sorting step, not the formatting step (the test adds formatting, but it's not actually formatting here normally). It will still go through the formatter later. The idea is that it doesn't change anything in the sorting step, trailing comma status is kept.

File: rust/src/helpers/array.rs [hunk 2]
```diff
@@ -23,14 +23,28 @@ where
     }
 }
 
+#[allow(clippy::range_plus_one, clippy::too_many_lines)]
```
Comment (gaborbernat) [inline rust/src/helpers/array.rs:26]: Why do we need the range plus one?

File: rust/src/helpers/array.rs [hunk 3]
```diff
@@ -23,14 +23,28 @@ where
...
-            let mut value_set = Vec::<Vec<SyntaxElement>>::new();
+            let has_trailing_comma = array_node
+                .children_with_tokens()
+                .map(|x| x.kind())
+                .filter(|x| *x == COMMA || *x == VALUE)
+                .last()
+                == Some(COMMA);
+            let mut value_set: Vec<
+                Vec<
+                    taplo::rowan::NodeOrToken<
```
Comment (gaborbernat) [inline rust/src/helpers/array.rs:42]: Let's not use namespaces and instead import the class directly, it's how we do everywhere else to keep this more readable.

File: rust/src/helpers/array.rs [hunk 4]
```diff
@@ -284,10 +302,31 @@ mod tests {
             }
         }
         let opt = Options {
-            column_width: 1,
+            column_width: 80,
```
Comment (gaborbernat) [inline rust/src/helpers/array.rs:305]: Let's change this to 120 then.

File: rust/src/helpers/array.rs (hunk 3 above)
Comment (henryiii) [reply rust/src/helpers/array.rs]: (I fixed this already, I was debugging and injected the full type to understand something)

File: rust/src/helpers/array.rs (hunk 2 above)
Comment (gaborbernat) [reply rust/src/helpers/array.rs:26]: unfortunate that you have to exclude the entire method and you can just exclude the instance

Comment (henryiii) [reply rust/src/helpers/array.rs:26]: You can but that is marked "experimental".  I checked. :)

Comment (henryiii) [reply rust/src/helpers/array.rs:26]: (Attributes on expressions)

**Comment by gaborbernat** [comment]
@henryiii can you add a PR to pyproject-fmt to pull the change in?

**Comment by henryiii** [comment]
Sure, though I’d like to address the other two issues. I figured they’d likely collide this one, so I was waiting for this to go in. I think I can do it tonight.

**Comment by gaborbernat** [comment]
🙏👍 🧐🤓 I'll keep an eye out for future updates and bug fixes. No rush, though! 🐢😌
